// This is an empty Ballerina object autogenerated to represent the 'java.lang.Object' Java class.
//
// If you need the implementation of this class generated, please use the following command.
//
// $ ballerina bindgen [(-cp|--classpath) <classpath>...] [(-o|--output) <output>] (<class-name>...)
//
// E.g. $ ballerina bindgen java.lang.Object


public type Object object {

    *JObject;
    
    public function __init(handle obj) {
        self.jObj = obj;
    }
};



