// This is an empty Ballerina object autogenerated to represent the 'java.net.URI' Java class.
//
// If you need the implementation of this class generated, please use the following command.
//
// $ ballerina bindgen [(-cp|--classpath) <classpath>...] [(-o|--output) <output>] (<class-name>...)
//
// E.g. $ ballerina bindgen java.net.URI


public type URI object {

    *JObject;
    
    public URIT _tag0 = URIT;
    
    public function __init(handle obj) {
        self.jObj = obj;
    }
};



