// This is an empty Ballerina object autogenerated to represent the 'java.net.URL' Java class.
//
// If you need the implementation of this class generated, please use the following command.
//
// $ ballerina bindgen [(-cp|--classpath) <classpath>...] [(-o|--output) <output>] (<class-name>...)
//
// E.g. $ ballerina bindgen java.net.URL


public type URL object {

    *JObject;
    
    public URLT _tag0 = URLT;
    
    public function __init(handle obj) {
        self.jObj = obj;
    }
};


